# A name for your workflow
name: Build Cross-Platform Executables

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Windows build job
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install Node.js dependencies inside the correct folder
          npm install 

      - name: Build Windows executable
        run: >
          pyinstaller --onefile 
          --name="xPedite" 
          --add-data "templates;templates" 
          --add-data "puppeteer_pdf_generator;puppeteer_pdf_generator"
          --add-data "node_modules;node_modules"
          --hidden-import="reportlab.graphics.barcode.code93" 
          --hidden-import="reportlab.graphics.barcode.code128" 
          liveServer.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: xPedite-Windows
          path: dist/xPedite.exe

  # macOS build job
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install Node.js dependencies inside the correct folder
          npm install --prefix puppeteer_pdf_generator

      - name: Build macOS application
        run: >
          pyinstaller --onefile --windowed 
          --name="xPedite" 
          --add-data "templates:templates" 
          --add-data "puppeteer_pdf_generator:puppeteer_pdf_generator"
          --add-data "node_modules:node_modules"
          --hidden-import="reportlab.graphics.barcode.code93" 
          --hidden-import="reportlab.graphics.barcode.code128" 
          liveServer.py

      - name: Zip the .app
        run: zip -r xPedite-macOS.zip dist/xPedite.app

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: xPedite-macOS
          path: xPedite-macOS.zip
