name: Build Python Executables

on:
push:
  branches: [ "main" ]
workflow_dispatch:

jobs:
build-windows:
  runs-on: windows-latest
  steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        npm install

    - name: Build Windows executable
      run: pyinstaller --onefile --name="xPedite" --add-data "templates;templates" liveServer.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: xPedite-Windows
        path: dist/xPedite.exe

build-macos:
  runs-on: macos-latest
  steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        npm install

    - name: Build macOS application
      run: pyinstaller --onefile --name="xPedite" --add-data "templates:templates" liveServer.py

    - name: Zip the .app
      run: zip -r xPedite-macOS.zip dist/xPedite.app

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: xPedite-macOS
        path: xPedite-macOS.zip