name: Debug Repository State

on:
  workflow_dispatch: # Allows us to run this manually

jobs:
  debug-job:
    runs-on: windows-latest # Must be windows-latest to match your error log
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: 1. Show the Current Directory
        run: echo "I am in this directory:" && pwd

      - name: 2. List all files recursively
        run: |
          echo "Listing all files and folders from the root..."
          dir /s
        shell: cmd

      - name: 3. Print contents of the REAL workflow file
        run: |
          echo "Displaying the contents of the main workflow file that the runner sees:"
          type .github\workflows\build-executables.yml
          # IMPORTANT: If your real workflow file has a different name, change "build-executables.yml" to the correct name.
        shell: cmd
